ALTER TABLE "Quote"
ADD COLUMN IF NOT EXISTS "totalDa" INTEGER;

UPDATE "Quote"
SET "totalDa" = COALESCE("totalDa", "totalMad", 0);

ALTER TABLE "Quote"
ALTER COLUMN "totalDa" SET DEFAULT 0;

ALTER TABLE "Quote"
ALTER COLUMN "totalDa" SET NOT NULL;

ALTER TABLE "Quote"
DROP COLUMN IF EXISTS "totalMad";
